<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>HcmIdentityProvisioning.Domain</PackageId>
    <Version>1.1.0</Version>
    <Authors>Hcm Identity Provisioning Team</Authors>
    <Description>Enterprise Domain Models and Ports for HCM Identity Provisioning</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

</Project>
