<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HcmIdentityProvisioning.Domain\HcmIdentityProvisioning.Domain.csproj" />
    <ProjectReference Include="..\HcmIdentityProvisioning.Application\HcmIdentityProvisioning.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RulesEngine" Version="5.0.6" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Rules\rules.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
